apiVersion: apps/v1
kind: Deployment
metadata:
  name: construction-genai
  labels:
    app: construction-genai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: construction-genai
  template:
    metadata:
      labels:
        app: construction-genai
    spec:
      containers:
        - name: construction-genai
          image: anshulyd26/construction-genai:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api-key
                  key: api-key
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
