apiVersion: v1
kind: Service
metadata:
  name: construction-genai
  labels:
    app: construction-genai
spec:
  type: LoadBalancer
  selector:
    app: construction-genai
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
